---
- name: Install packages and gems on localhost
  hosts: localhost
  become: yes # Use sudo to become the root user

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install necessary packages
      ansible.builtin.apt:
        name:
          - libmysqlclient-dev
          - mysql-client
          - ruby-full
          - libyaml-dev
          - build-essential
          - default-libmysqlclient-dev
          - libvips
          - pkg-config
          - mysql-server
          - inotify-tools
          - openssh-server
          - wireguard
          - net-tools
        state: present
    - name: Enable service ssh server and ensure it is not masked
      ansible.builtin.systemd_service:
        name: ssh
        enabled: true

    - name: Make sure ssh service is running
      ansible.builtin.systemd:
        name: ssh
        state: started

    - name: Make sure wireguard wg-quick@wg0 service is running
      ansible.builtin.systemd:
        name: wg-quick@wg0
        state: enabled
