---
- name: Install packages and gems on localhost
  hosts: localhost
  become: yes # Use sudo to become the root user

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install necessary packages
      ansible.builtin.apt:
        name:
          - libmysqlclient-dev
          - mysql-client
          - ruby-full
          - nodejs
          - npm
          - libyaml-dev
          - build-essential
          - default-libmysqlclient-dev
          - libvips
          - pkg-config
          - inotify-tools
          - openssh-server
          - wireguard
          - net-tools
        state: present

    - name: Install Rails gem
      ansible.builtin.gem:
        name: rails
        state: present
        user_install: no # Install the gem system-wide

    - name: Install Bundler gem
      ansible.builtin.gem:
        name: bundler
        state: present
        user_install: no # Install the gem system-wide

    - name: Install required packages for Docker
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg
        state: present
        update_cache: yes

    - name: Add Docker’s official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Set up the stable repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        state: present
        update_cache: yes

    - name: Install Docker Engine and components
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin # Updated to include Docker Compose as an apt package
        state: present
        update_cache: yes

    - name: Ensure Docker service is started and enabled
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes
