---
- hosts: all
  become: true
  tasks:
    - name: Install required packages
      apt:
        name:
          - wireguard
          - linux-headers-generic
        state: present
        update_cache: yes

    - name: Create WireGuard configuration directory
      file:
        path: /etc/wireguard
        state: directory
        mode: '0755'

    - name: Generate server's WireGuard private key
      shell: wg genkey | tee /etc/wireguard/private.key
      register: server_private_key

    - name: Generate server's WireGuard public key
      shell: cat /etc/wireguard/private.key | wg pubkey | tee /etc/wireguard/public.key
      register: server_public_key

    - name: Configure WireGuard interface
      template:
        src: wg0.conf.j2
        dest: /etc/wireguard/wg0.conf
      vars:
        server_private_key: "{{ server_private_key.stdout }}"
        server_public_ip: "{{ ansible_host }}"
        docker_subnet: "172.17.0.0/16"
        incus_subnet: "10.34.129.0/24"

    - name: Enable and start WireGuard interface
      systemd:
        name: wg-quick@wg0
        state: started
        enabled: yes

    - name: Open WireGuard port in the firewall
      ufw:
        rule: allow
        port: 51820
        proto: udp